background            #202433
foreground            #eceffd
cursor                #ffebee
selection_background  #fcf6e8
color0                #03063c
color8                #C08285
color1                #EF5350
color9                #d94a8a
color2                #69F0AE
color10               #daffa8
color3                #fdcd5e
color11               #fee6a8
color4                #525fb8
color12               #b1bdf9
color5                #7E4F5E
color13               #fda4cc
color6                #F7CCAC
color14               #a4bc86
color7                #eceffc
color15               #f6ffec
selection_foreground #222436
